pybo/views/answer_views.py
from datetime import datetime
from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Question, Answer
from ..forms import AnswerForm
from .auth_views import login_required

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>', methods=("POST",))
@login_required
def create(question_id):
	question = Question.query.get_or_404(question_id)
	form = AnswerForm()
	if g.user == question.user:
		flash("자신의 질문에는 답변할 수 없습니다.")
		return redirect(url_for('question.detail',question_id=question_id))
	if form.validate_on_submit():
		content = request.form['content']
		answer = Answer(content=content, create_date=datetime.now(), user=g.user)
		question.answer_set.append(answer)
		db.session.commit()
		return redirect('{}#answer_{}'.format(url_for('question.detail',question_id=question_id), answer.id))
	return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/modify/<int:answer_id>/', methods=("GET","POST"))
@login_required
def modify(answer_id):
	answer=Answer.query.get_or_404(answer_id)
	if g.user != answer.user:
		flash('수정권한이 없습니다.')
		return redirect(url_for('question.detail', question_id=answer.question.id))
	if request.method=="POST":
		form = AnswerForm()
		if form.validate_on_submit():
			form.populate_obj(answer)
			answer.modify_date=datetime.now()
			db.session.commit()
			return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=answer.question.id), answer.id))
	form = AnswerForm(obj=answer)
	return render_template('question/answer_form.html', answer=answer, form=form)

@bp.route('/delete/<int:answer_id>/')
@login_required
def delete(answer_id):
	answer=Answer.query.get_or_404(answer_id)
	question_id = answer.question.id
	if g.user != answer.user:
		flash('삭제권한이 없습니다.')
		return redirect(url_for('question.detail', question_id=question_id))
	else:
		db.session.delete(answer)
		db.session.commit()
		return redirect(url_for('question.detail', question_id=question_id))

pybo/views/comment_views.py
from datetime import datetime

from flask import Blueprint, render_template, url_for, request, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import CommentForm
from pybo.models import Question, Answer, Comment
from pybo.views.auth_views import login_required

bp = Blueprint('comment', __name__, url_prefix="/comment")

# 질문 코멘트
@bp.route('/create/question/<int:question_id>', methods=("GET","POST"))
@login_required
def create_question(question_id):
	form = CommentForm()
	question = Question.query.get_or_404(question_id)
	if request.method == "POST" and form.validate_on_submit():
		comment = Comment(user=g.user, content = form.content.data, create_date = datetime.now(), question=question)
		db.session.add(comment)
		db.session.commit()
		return redirect('{}#comment_{}'.format(url_for('question.detail',question_id=question_id), comment.id))
	return render_template('comment/comment_form.html', form=form)

@bp.route('/modify/question/<int:comment_id>', methods=("GET", "POST"))
@login_required
def modify_question(comment_id):
	comment = Comment.query.get_or_404(comment_id)
	if g.user != comment.user:
		flash('수정권한이 없습니다.')
		return redirect(url_for('question.detail', question_id=comment.question.id))
	if request.method=="POST":
		form = CommentForm()
		if form.validate_on_submit():
			form.populate_obj(comment)
			comment.modify_date = datetime.now()
			db.session.commit()
			return redirect('{}#comment_{}'.format(url_for('question.detail',question_id=comment.question.id), comment.id))
	else:
		form = CommentForm(obj=comment)
	return render_template('comment/comment_form.html', form=form)

@bp.route('/delete/question/<int:comment_id>')
@login_required
def delete_question(comment_id):
	comment = Comment.query.get_or_404(comment_id)
	question_id = comment.question.id
	if g.user != comment.user:
		flash('삭제권한이 없습니다.')
		return redirect(url_for('question.detail', question_id=question_id))
	db.session.delete(comment)
	db.session.commit()
	return redirect(url_for('question.detail', question_id=question_id))

# 답변 코멘트
@bp.route('/create/answer/<int:answer_id>', methods=("GET","POST"))
@login_required
def create_answer(answer_id):
	form = CommentForm()
	answer = Answer.query.get_or_404(answer_id)
	if request.method == "POST" and form.validate_on_submit():
		comment = Comment(user=g.user, content = form.content.data, create_date = datetime.now(), answer=answer)
		db.session.add(comment)
		db.session.commit()
		return redirect('{}#comment_{}'.format(url_for('question.detail',question_id=answer.question.id), comment.id))
	return render_template('comment/comment_form.html', form=form)

@bp.route('/modify/answer/<int:comment_id>', methods=("GET", "POST"))
@login_required
def modify_answer(comment_id):
	comment = Comment.query.get_or_404(comment_id)
	if g.user != comment.user:
		flash('수정권한이 없습니다.')
		return redirect(url_for('question.detail', question_id=comment.answer.question.id))
	if request.method=="POST":
		form = CommentForm()
		if form.validate_on_submit():
			form.populate_obj(comment)
			comment.modify_date = datetime.now()
			db.session.commit()
			return redirect('{}#comment_{}'.format(url_for('question.detail',question_id=comment.answer.question.id), comment.id))
	else:
		form = CommentForm(obj=comment)
	return render_template('comment/comment_form.html', form=form)

@bp.route('/delete/answer/<int:comment_id>')
@login_required
def delete_answer(comment_id):
	comment = Comment.query.get_or_404(comment_id)
	question_id = comment.answer.question.id
	if g.user != comment.user:
		flash('삭제권한이 없습니다.')
		return redirect(url_for('question.detail', question_id=question_id))
	db.session.delete(comment)
	db.session.commit()
	return redirect(url_for('question.detail', question_id=question_id))

pybo/views/question_views.py
from datetime import datetime
from flask import Blueprint, render_template, request, url_for, g, flash, make_response
from werkzeug.utils import redirect
from .. import db #pybo/__init__.py의 db 객체 load
from pybo.models import Question, Answer, User, question_voter
from ..forms import QuestionForm, AnswerForm
from sqlalchemy import func

from .answer_views import login_required

bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list/setcookie', methods=["GET", "POST"])
def setcookie():
	if request.method == "POST":
		page = request.form["page"]
		ss = request.form["ss"]
		kw = request.form["kw"]
		so = request.form["so"]
		
		res = make_response(redirect(url_for('main.index')))
		res.set_cookie("page", page)
		res.set_cookie("ss", ss)
		res.set_cookie("kw", kw)
		res.set_cookie("so", so)

	return res

@bp.route('/list/')
def _list():
	clear = request.args.get('clear', type=int, default=0)
	if clear == 1:
		res = make_response(redirect(url_for('main.index')))
		res.set_cookie("page", '1')
		res.set_cookie("ss", 'qs')
		res.set_cookie("kw", '')
		res.set_cookie("so", 'rc')
		return res

	page = request.cookies.get('page') # default=1
	if page: page = int(page)
	ss = request.cookies.get('ss') # default='qs'
	kw = request.cookies.get('kw') # default=''
	so = request.cookies.get('so') # default='rc'

	#print("page : {}".format(page))
	#print("ss : {}".format(ss))
	#print("kw : {}".format(kw))
	#print("so : {}".format(so))

	if so=="rm": #recommend
		sub_query= db.session.query(question_voter.c.question_id, func.count('*').label('num_voter')).group_by(question_voter.c.question_id).subquery()
		question_list = Question.query.outerjoin(sub_query, Question.id==sub_query.c.question_id).order_by(sub_query.c.num_voter.desc(), Question.create_date.desc())
	elif so=="po": #popular
		sub_query = db.session.query(Answer.question_id, func.count('*').label('num_answer')).group_by(Answer.question_id).subquery()
		question_list = Question.query.outerjoin(sub_query, Question.id==sub_query.c.question_id).order_by(sub_query.c.num_answer.desc(), Question.create_date.desc())
	else: #최근순(recent)
		question_list = Question.query.order_by(Question.create_date.desc())

	if kw: #검색 내용에 따라 조회 내역 재작성
		search = '%%{}%%'.format(kw)
		sub_query = db.session.query(Answer.question_id, Answer.content, User.username).join(User, Answer.user_id==User.id).subquery()
		question_list = question_list.join(User).outerjoin(sub_query, sub_query.c.question_id==Question.id)

		if ss=="qc":
			question_list=question_list.filter(Question.content.ilike(search)).distinct() #질문 내용
		elif ss=="qu":
			question_list=question_list.filter(User.username.ilike(search)).distinct() #질문 작성자
		elif ss=="ac":
			question_list=question_list.filter(sub_query.c.content.ilike(search)).distinct() #답변 내용
		elif ss=="au":
			question_list=question_list.filter(sub_query.c.username.ilike(search)).distinct() #답변 작성자
		else:
			question_list=question_list.filter(Question.subject.ilike(search)).distinct() #질문 제목

	question_list=question_list.paginate(page, per_page=10) #Pagination 객체 생성
	return render_template('question/question_list.html', question_list = question_list, page=page, ss=ss, kw=kw, so=so)

@bp.route('/detail/<int:question_id>/')
def detail(question_id):
	form = AnswerForm()
	question=Question.query.get_or_404(question_id)
	return render_template('question/question_detail.html',question=question, form=form)

@bp.route('/create/', methods=('GET','POST'))
@login_required
def create():
	form = QuestionForm()
	if request.method=="POST" and form.validate_on_submit():
		question=Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user)
		db.session.add(question)
		db.session.commit()
		return redirect(url_for('main.index'))
	return render_template('question/question_form.html', form=form)

@bp.route('/modify/<int:question_id>/', methods=("GET","POST"))
@login_required
def modify(question_id):
	question=Question.query.get_or_404(question_id)
	if g.user != question.user:
		flash('수정권한이 없습니다.')
		return redirect(url_for('question.detail', question_id=question_id))
	if request.method=="POST":
		form = QuestionForm()
		if form.validate_on_submit():
			form.populate_obj(question)
			question.modify_date=datetime.now()
			db.session.commit()
			return redirect(url_for('question.detail', question_id=question_id))
	form = QuestionForm(obj=question)
	return render_template('question/question_form.html', form=form)

@bp.route('/delete/<int:question_id>/')
@login_required
def delete(question_id):
	question=Question.query.get_or_404(question_id)
	if g.user != question.user:
		flash('삭제권한이 없습니다.')
		return redirect(url_for('question.detail', question_id=question_id))
	else:
		db.session.delete(question)
		db.session.commit()
		return redirect(url_for('question._list'))

pybo/views/vote_views.py
from flask import Blueprint, url_for, flash, g
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Question, Answer, question_voter, answer_voter
from pybo.views.auth_views import login_required

bp = Blueprint('vote', __name__, url_prefix="/vote")

@bp.route('/question/<int:question_id>')
@login_required
def question(question_id):
	_question = Question.query.get_or_404(question_id)
	vote_already = db.session.query(question_voter).filter(question_voter.c.user_id==g.user.id, question_voter.c.question_id==question_id)
	if g.user == _question.user:
		flash('본인이 작성한 글은 추천할 수 없습니다.')
	elif vote_already.all():
		vote_already.delete() # 이미 존재하는 경우 좋아요 취소
		db.session.commit()
	
	else:
		_question.voter.append(g.user) # 좋아요 기록
		db.session.commit()
	return redirect('{}#vote_question'.format(url_for('question.detail', question_id = question_id)))

@bp.route('/answer/<int:answer_id>')
@login_required
def answer(answer_id):
	_answer = Answer.query.get_or_404(answer_id)
	vote_already = db.session.query(answer_voter).filter(answer_voter.c.user_id==g.user.id, answer_voter.c.answer_id==answer_id)
	if g.user == _answer.user:
		flash('본인이 작성한 글은 추천할 수 없습니다.')
	elif vote_already.all():
		vote_already.delete() # 이미 존재하는 경우 좋아요 취소
		db.session.commit()
	
	else:
		_answer.voter.append(g.user) # 좋아요 기록
		db.session.commit()
	return redirect('{}#vote_answer_{}'.format(url_for('question.detail', question_id = _answer.question.id),answer_id))

pybo/templates/question/answer_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
	<form method="post" class="post-form">
		{{form.csrf_token}}
		{% include "form_errors.html" %}
		<div class="form-group">
			<label for="content">답변내용</label>
			<textarea class="form-control" name="content" id="content" rows="10">{{form.content.data or ''}}</textarea>
		</div>
		<button type="submit" class="btn btn-primary">저장하기</button>
	</form>
</div>
{% endblock %}

pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    {% include "form_errors.html" %}
    <h2 class="border-bottom py-2">{{question.subject}}</h2>
    
    <div class="row my-3">
        <div class="col-1"> <!--추천 영역-->
            <a name="vote_question"></a>
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter|length}}</div>
            <a href="#" data-uri="{{url_for('vote.question', question_id=question.id)}}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"> <!--기존 영역-->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{question.content|markdown}}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2">
                            <div class="mb-2">{{question.user.username}}</div>
                            {% if question.modify_date %}
                            <div>{{question.modify_date|datetime}} (수정됨)</div>
                            {% else %}
                            <div>{{question.create_date|datetime}}</div>
                            {% endif %}
                        </div>
                    </div>
                    {% if g.user ==question.user %}
                    <div class="my-3">
                        <a href="{{url_for('question.modify', question_id=question.id)}}" class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{{url_for('question.delete',question_id=question.id)}}">삭제</a>
                    </div>
                    {% endif %}
                    
                    <!--질문 댓글-->
                    {% if question.comment_set|length > 0 %}
                    <div class="mt-3">
                    {% for comment in question.comment_set %}
                        <a name="comment_{{comment.id}}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{comment.content|markdown}}</span>
                            <span>
                                - {{ comment.user.username}}, 
                                {% if comment.modify_date %}
                                {{comment.modify_date|datetime}} (수정됨)
                                {% else %}
                                {{comment.create_date|datetime}}
                                {% endif %}
                            </span>
                            {% if g.user == comment.user %}
                            <a href="{{url_for('comment.modify_question', comment_id=comment.id)}}" class="small">수정</a>
                            <a href="#" class="small delete" data-uri="{{url_for('comment.delete_question', comment_id=comment.id)}}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{{url_for('comment.create_question', question_id=question.id)}}" class="small"><small>댓글 추가 ..</small></a>
                    </div>
                    <!--질문 댓글 End-->
                    
                </div>
            </div>
        </div>
    </div>
    
    <h5 class="border-bottom my-3 py-2">{{question.answer_set|length}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set %}
    <a name="answer_{{answer.id}}"></a>
    <div class="row my-3">
        <div class="col-1"> <!--추천 영역-->
            <a name="vote_answer_{{answer.id}}"></a>
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter|length}}</div>
            <a href="#" data-uri="{{url_for('vote.answer', answer_id=answer.id)}}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
    
        <div class="col-11"> <!--기존 영역-->
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{answer.content|markdown}}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2">
                            <div class="mb-2">{{answer.user.username}}</div>
                            {% if answer.modify_date %}
                            <div>{{answer.modify_date|datetime}} (수정됨)</div>
                            {% else %}
                            <div>{{answer.create_date|datetime}}</div>
                            {% endif %}
                        </div>
                    </div>
                    {% if g.user ==answer.user %}
                    <div class="my-3">
                        <a href="{{url_for('answer.modify', answer_id=answer.id)}}" class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{{url_for('answer.delete',answer_id=answer.id)}}">삭제</a>
                    </div>
                    {% endif %}
                    
                    <!--답변 댓글-->
                    {% if answer.comment_set|length > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set %}
                    <a name="comment_{{comment.id}}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{comment.content|markdown}}</span>
                            <span>
                                - {{ comment.user.username}}, 
                                {% if comment.modify_date %}
                                {{comment.modify_date|datetime}} (수정됨)
                                {% else %}
                                {{comment.create_date|datetime}}
                                {% endif %}
                            </span>
                            {% if g.user == comment.user %}
                            <a href="{{url_for('comment.modify_answer', comment_id=comment.id)}}" class="small">수정</a>
                            <a href="#" class="small delete" data-uri="{{url_for('comment.delete_answer', comment_id=comment.id)}}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{{url_for('comment.create_answer', answer_id=answer.id)}}" class="small"><small>댓글 추가 ..</small></a>
                    </div>
                    <!--답변 댓글 End-->
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{url_for('answer.create', question_id=question.id)}}" method="post" class="my-3">
        {{form.csrf_token}}
        <div class="form-group">

            <textarea {% if not g.user %}disabled{% endif %} name="content" id="content" class="form-control" rows="15"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
        <div class="form-row float-right">
            <a type="button" href="{{url_for('question._list')}}" class="btn btn-primary">돌아가기</a>
        </div>
        
    </form>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
$(document).ready(function(){
    $(".delete").on('click', function(){
        if(confirm('정말로 삭제하시겠습니까?')){
            location.href=$(this).data('uri');
        }
    });
    $(".recommend").on('click', function(){
        location.href = $(this).data('uri');
    });
});
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
	<h4 class="border-bottom py-2">질문등록</h4>
	<form method="post" class="post-form my-3">
		{{form.csrf_token}}

		<!--오류표시-->
		{% for field, errors in form.errors.items() %}
		<div class="alert alert-danger" role="alert">
			<strong>{{form[field].label}}</strong>:{{', '.join(errors)}}
		</div>
		{% endfor %}
		
		<!--폼 구조-->
		<div class="form-group">
			<label for="subject">제목</label>
			<input type="text" class="form-control" name="subject" id="subject" value="{{form.subject.data or ''}}">
		</div>

		<div class="form-group">
			<label for="content">내용</label>
			<textarea type="text" class="form-control" name="content" id="content" rows="10" >{{form.content.data or ''}}</textarea>
		</div>

		<button type="submit" class="btn btn-primary">저장하기</button>
	</form>
</div>
{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    
    <div class="row justify-content-between my-3">
        <!--정렬 기능-->
        <div class="col-2">
            <select class="form-control so">
                <option value="rc" {% if so=='rc' %}selected{% endif %}>최신순</option>
                <option value="rm" {% if so=='rm' %}selected{% endif %}>추천순</option>
                <option value="po" {% if so=='po' %}selected{% endif %}>인기순</option>
            </select>
        </div>

        <!--검색 기능-->
        <div class="col-5 input-group">
            <select class="form-control ss">
                <option value="qs" {% if ss=='qs' %}selected{% endif %}>질문 제목</option>
                <option value="qc" {% if ss=='qc' %}selected{% endif %}>질문 내용</option>
                <option value="qu" {% if ss=='qu' %}selected{% endif %}>질문 작성자</option>
                <option value="ac" {% if ss=='ac' %}selected{% endif %}>답변 내용</option>
                <option value="au" {% if ss=='au' %}selected{% endif %}>답변 작성자</option>
            </select>
            <div class="w-10">
                <input type="text" class="form-control kw" value="{{ kw or '' }}">
            </div>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <!--목록 Table-->
    <table class="table">
        <thead>
        <tr class="thead-dark text-center">
            <th>번호</th>
            <th>추천</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list.items %}
        <tr class="text-center">
            <td>{{ question_list.total - ((question_list.page-1)*question_list.per_page)-loop.index0 }}</td>
            <td>
                {% if question.voter|length %}
                <span class="badge badge-warning px-2 py-1">{{ question.voter|length }}</span>
                {% endif %}
            </td>
            <td class="text-left">
                <a href="{{url_for('question.detail', question_id=question.id)}}">{{question.subject}}</a>
                {% if question.answer_set|length > 0 %}
                <span class="text-danger mall ml-2">{{question.answer_set|length}}</span>
                {% endif %}
            </td>
            <td>{{ question.user.username }}</td>
            <td>{{ question.create_date|datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!--페이징 처리-->
    <ul class="pagination justify-content-center">
        <!--이전 페이지-->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.prev_num }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_num in question_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != question_list.page %}
                <!--현재 페이지 아닌 경우 하이퍼링크 이동 처리-->
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_num }}" href="#">{{page_num}}</a>
                </li>
                {% else %}
                <!--현재 페이지인 경우 하이퍼링크 #처리-->
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{page_num}}</a>
                </li>
                {% endif %}
            {% else %}
            <!--페이지가 많으면 Pagination이 일부만 보여주고 나머지 None 처리-->
            <!--페이지가 너무 많으면 현재페이지 기준 좌우 보여주고 나머지는 ...으로 표기-->
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
            {% endif %}
        {% endfor %}
        <!--다음 페이지-->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_num }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <ul class="pagination justify-content-center">
        <input style="width:20%;" class="form-control mr-2" name="page_text" id="page_text">
        <a type="button" href="#" class="page_move btn btn-primary">이동하기</a>
    </ul>
    </ul>
    <!--페이징 처리 종료-->

    <a href="{{url_for('question.create')}}" class="btn btn-primary">질문 등록하기</a>
</div>
<form id="searchform" method="post" action="{{ url_for('question.setcookie') }}">
    <input type="hidden" id="ss" name="ss" value="{{ ss }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or ''}}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}

{% block script %}
<script type="text/javascript">
$(document).ready(function(){
    $(".page_move").on('click', function(){
        $("#ss").val($(".ss").val());
        $("#kw").val($(".kw").val());
        $("#page").val($('#page_text').val()); //Form#searchform에 page값 넣음
        $("#so").val($(".so").val());
        $("#searchform").submit(); //페이지 이동요청
    });

    $(".page-link").on('click', function(){
        $("#ss").val($(".ss").val());
        $("#kw").val($(".kw").val());
        $("#page").val($(this).data("page")); //Form#searchform에 page값 넣음
        $("#so").val($(".so").val());
        $("#searchform").submit(); //페이지 이동요청
    });

    $("#btn_search").on('click', function(){
        $("#ss").val($(".ss").val()); //검색 타입
        $("#kw").val($(".kw").val()); //Form#searchform에 kw값 넣음
        $("#page").val(1); // 검색기능 사용 시 1페이지로 이동
        $("#so").val($(".so").val());
        $("#searchform").submit(); //페이지 이동요청
    })

    $(".so").on('change', function(){
        $("#ss").val($(".ss").val()); //검색 타입
        $("#kw").val($(".kw").val()); //Form#searchform에 kw값 넣음
        $('#page').val(1);
        $("#so").val($(this).val());
        $("#searchform").submit();
    })
});

$(".kw").keyup(function(e){
    if(e.keyCode==13){
        $("#ss").val($(".ss").val());
            $("#kw").val($(".kw").val());
            $("#page").val(1);
            $("#searchform").submit();
    }
});

$("#page_text").keyup(function(e){
    if(e.keyCode==13){
        $("#page").val($('#page_text').val());
        $("#searchform").submit();
    }
});
</script>
{% endblock %}